### ISSUE TITLE
CRITICAL - Service missing

### ISSUE THREAD

**Issue by dephillipsmichael** [haroldwaters/salesman#1]
Are you tired of pesky git users filing issues on YOUR repo!?  Do they say things like, “this software crashes!” and “a toddler could write better code!”?  

Well, it’s time to relax and let us handle it.

Hi! We’re Git Fucked.  The very first git issue defense service.  

The best defense is a good offense, and so we attack a git user with frivolous law suits, social smear campaigns, and DDOS attack their software for even daring to open up an issue up on YOUR repo! 

Science shows that 10% of the time, it works every time! So please sign up and pay us, otherwise we will destroy your repo with thousands of baseless git issues. 

Only gift card payments to Danny Flash’s Shirt Emporium are accepted at this time, thank you.

**Comment by harrietfigueroa** [comment]
Bitcoin assassin hired for issue filer.
